# Generated by Django 5.1.3 on 2024-11-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emailanalysis_confidence_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailanalysis',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
    ]
