# Generated by Django 5.1.3 on 2024-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emailanalysis_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailanalysis',
            name='user',
        ),
        migrations.AlterField(
            model_name='emailanalysis',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailanalysis',
            name='is_phishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailanalysis',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
